executor: LocalExecutor

webserver:
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        nodePort: 30002
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin123

scheduler:
  replicas: 1

flower:
  enabled: false
  
statsd:
  enabled: false

pgbouncer:
  enabled: false

redis:
  enabled: false

triggerer:
  enabled: false

postgresql:
  enabled: true
  auth:
    postgresPassword: postgres
    database: airflow

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: false

logs:
  persistence:
    enabled: false

workers:
  persistence:
    enabled: false

config:
  core:
    load_examples: 'True'
  webserver:
    expose_config: 'True'