version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./data:/data
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlruns
    command: >
      mlflow server 
      --backend-store-uri sqlite:///mlflow.db 
      --default-artifact-root /mlruns 
      --host 0.0.0.0 
      --port 5000
