kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mlops-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
    - containerPort: 30001
      hostPort: 30001
      protocol: TCP
    - containerPort: 30002
      hostPort: 30002
      protocol: TCP
    - containerPort: 30003
      hostPort: 30003
      protocol: TCP
    - containerPort: 30004
      hostPort: 30004
      protocol: TCP
    extraMounts:
      - hostPath: ./data
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: ./data
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: ./data
        containerPath: /data