apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: python:3.9-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            pip install mlflow==2.5.0 psycopg2-binary boto3
            mlflow server \
              --backend-store-uri sqlite:///mlflow.db \
              --default-artifact-root /mlflow-artifacts \
              --host 0.0.0.0 \
              --port 5000
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow-artifacts
        - name: mlflow-db
          mountPath: /mlflow.db
      volumes:
      - name: mlflow-data
        persistentVolumeClaim:
          claimName: mlflow-pvc
      - name: mlflow-db
        emptyDir: {}