apiVersion: v1
kind: ConfigMap
metadata:
  name: model-server-config
  namespace: serving
data:
  MODEL_PATH: "/models/best_model.pkl"
  MLFLOW_TRACKING_URI: "http://mlflow-service.mlflow:5000"
---
apiVersion: apps/v1
metadata:
  name: model-server
  namespace: serving
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-server
        image: python:3.9-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            pip install fastapi uvicorn pandas numpy scikit-learn mlflow pydantic
            cd /app
            python model_server.py
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: model-server-config
              key: MODEL_PATH
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            configMapKeyRef:
              name: model-server-config
              key: MLFLOW_TRACKING_URI
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: model-storage
          mountPath: /models
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
      volumes:
      - name: app-code
        configMap:
          name: model-server-code
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: model-server-service
  namespace: serving
spec:
  type: NodePort
  selector:
    app: model-server
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30005
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
  namespace: serving
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: model-server-hpa
  namespace: serving
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: model-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80