apiVersion: v1
kind: Service
metadata:
  name: model-serving-service
  namespace: serving
spec:
  type: NodePort
  selector:
    app: model-server
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30005